// Generates the curriculum summary shown on the public landing page.
//
// The landing page states the *shape* of the framework (how many concepts, how
// many stages, which strands) but never lists the levels themselves. Those
// numbers move: the framework is revised as curriculum research lands, and
// PR #517 alone changed every level number below stage 3. Hand-written copy
// would silently go stale the first time that happens, so the counts are
// derived from backend/src/config/curriculumMap.ts — the same file the rest of
// the system treats as the source of truth — and regenerated on every build.
//
// Only aggregates are emitted. Per-level content readiness (which levels have
// questions built and which do not) is deliberately NOT part of this file: it
// is operational detail, and the landing page is public.
//
// Usage: npx tsx scripts/build-curriculum-summary.ts
// Runs automatically as the frontend's prebuild step.

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { CURRICULUM_MAPPING } from '../backend/src/config/curriculumMap.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const OUT = path.join(ROOT, 'frontend', 'src', 'data', 'curriculumSummary.json');

/** Lowest and highest age appearing in any "3-4"-style ageGroup band. */
function ageRange(bands: string[]): { min: number; max: number } {
  const ages = bands.flatMap((b) => b.split('-').map(Number)).filter(Number.isFinite);
  return { min: Math.min(...ages), max: Math.max(...ages) };
}

function main() {
  const levels = Object.values(CURRICULUM_MAPPING);
  if (levels.length === 0) {
    console.error('CURRICULUM_MAPPING is empty — refusing to write an empty summary.');
    process.exit(1);
  }

  const strandCounts = new Map<string, number>();
  const stageAges = new Map<number, Set<string>>();
  for (const level of levels) {
    strandCounts.set(level.strand, (strandCounts.get(level.strand) ?? 0) + 1);
    if (!stageAges.has(level.stage)) stageAges.set(level.stage, new Set());
    stageAges.get(level.stage)!.add(level.ageGroup);
  }

  const { min, max } = ageRange(levels.map((l) => l.ageGroup));

  const summary = {
    // Regenerated by scripts/build-curriculum-summary.ts — do not edit by hand.
    totalConcepts: levels.length,
    totalStages: stageAges.size,
    totalStrands: strandCounts.size,
    ageMin: min,
    ageMax: max,
    strands: [...strandCounts.entries()]
      .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
      .map(([name, count]) => ({ name, count })),
  };

  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, JSON.stringify(summary, null, 2) + '\n');
  console.log(
    `[curriculum-summary] ${summary.totalConcepts} concepts, ${summary.totalStages} stages, ` +
      `${summary.totalStrands} strands (ages ${min}-${max}) -> ${path.relative(ROOT, OUT)}`
  );
}

main();
